/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in mature projects and checked in here so
// the workspace typecheck works before the first local Next build.
